Public Class Form1
    Private Sub TextBox1_TextChanged(sender As Object, e As EventArgs) Handles TextBox1.TextChanged

    End Sub

    Private Sub Form1_Load(sender As Object, e As EventArgs) Handles MyBase.Load
        Dim NewLine As String
        NewLine = System.Environment.NewLine
        For i As Integer = 30 To 50 Step 5

            'TextBox1.AppendText("'If ComboBox3.SelectedItem.ToString= " & "'4-0" & i.ToString & "'" & NewLine)
            'TextBox1.AppendText("'If ComboBox3.SelectedItem.ToString= " & "'5-0" & i.ToString & "'" & NewLine)
            TextBox1.AppendText("'If ComboBox3.SelectedItem.ToString= " & "'16-0" & i.ToString & "'" & NewLine)

        Next

    End Sub
    'CHC
    '    If ComboBox4.SelectedItem.ToString = '4-06'
    'If ComboBox4.SelectedItem.ToString= '4-08'
    'If ComboBox4.SelectedItem.ToString = '4-010'
    'If ComboBox4.SelectedItem.ToString= '4-012'
    'If ComboBox4.SelectedItem.ToString = '4-014'
    'If ComboBox4.SelectedItem.ToString= '4-016'
    'If ComboBox4.SelectedItem.ToString = '4-018'
    'If ComboBox4.SelectedItem.ToString= '4-020'
    '    If ComboBox4.SelectedItem.ToString = '4-025'
    'If ComboBox4.SelectedItem.ToString= '4-030'
    'If ComboBox4.SelectedItem.ToString = '4-035
    'If ComboBox4.SelectedItem.ToString= '4-040'
    '    If ComboBox4.SelectedItem.ToString = '5-06'
    'If ComboBox4.SelectedItem.ToString= '5-08'
    'If ComboBox4.SelectedItem.ToString = '5-010'
    'If ComboBox4.SelectedItem.ToString= '5-012'
    'If ComboBox4.SelectedItem.ToString = '5-014'
    'If ComboBox4.SelectedItem.ToString= '5-016'
    'If ComboBox4.SelectedItem.ToString = '5-018'
    'If ComboBox4.SelectedItem.ToString= '5-020'
    '    If ComboBox4.SelectedItem.ToString = '5-025'
    'If ComboBox4.SelectedItem.ToString= '5-030'
    'If ComboBox4.SelectedItem.ToString = '5-035'
    'If ComboBox4.SelectedItem.ToString= '5-040'
    'If ComboBox4.SelectedItem.ToString = '5-045'
    'If ComboBox4.SelectedItem.ToString= '5-050'
    '    If ComboBox4.SelectedItem.ToString = '6-010'
    'If ComboBox4.SelectedItem.ToString= '6-012'
    'If ComboBox4.SelectedItem.ToString = '6-014'
    'If ComboBox4.SelectedItem.ToString= '6-016'
    'If ComboBox4.SelectedItem.ToString = '6-018'
    'If ComboBox4.SelectedItem.ToString= '6-020'
    '    If ComboBox4.SelectedItem.ToString = '6-025'
    'If ComboBox4.SelectedItem.ToString= '6-030'
    'If ComboBox4.SelectedItem.ToString = '6-035'
    'If ComboBox4.SelectedItem.ToString= '6-040'
    'If ComboBox4.SelectedItem.ToString = '6-045'
    'If ComboBox4.SelectedItem.ToString= '6-050'
    'If ComboBox4.SelectedItem.ToString = '6-055'
    'If ComboBox4.SelectedItem.ToString= '6-060'
    '    If ComboBox4.SelectedItem.ToString = '8-012'
    'If ComboBox4.SelectedItem.ToString= '8-014'
    'If ComboBox4.SelectedItem.ToString = '8-016'
    'If ComboBox4.SelectedItem.ToString= '8-018'
    'If ComboBox4.SelectedItem.ToString = '8-020'
    'If ComboBox4.SelectedItem.ToString = '8-025'
    'If ComboBox4.SelectedItem.ToString= '8-030'
    'If ComboBox4.SelectedItem.ToString = '8-035'
    'If ComboBox4.SelectedItem.ToString= '8-040'
    'If ComboBox4.SelectedItem.ToString = '8-045'
    'If ComboBox4.SelectedItem.ToString= '8-050'
    'If ComboBox4.SelectedItem.ToString = '8-055'
    'If ComboBox4.SelectedItem.ToString= '8-060'
    'If ComboBox4.SelectedItem.ToString = '8-065'
    'If ComboBox4.SelectedItem.ToString= '8-070'
    'If ComboBox4.SelectedItem.ToString = '8-075'
    'If ComboBox4.SelectedItem.ToString= '8-080'
    'If ComboBox4.SelectedItem.ToString = '8-090'
    'If ComboBox4.SelectedItem.ToString= '8-0100'
    '    If ComboBox4.SelectedItem.ToString = '10-025'
    'If ComboBox4.SelectedItem.ToString= '10-030'
    'If ComboBox4.SelectedItem.ToString = '10-035'
    'If ComboBox4.SelectedItem.ToString= '10-040'
    'If ComboBox4.SelectedItem.ToString = '10-045'
    'If ComboBox4.SelectedItem.ToString= '10-050'
    'If ComboBox4.SelectedItem.ToString = '10-055'
    'If ComboBox4.SelectedItem.ToString= '10-060'
    'If ComboBox4.SelectedItem.ToString = '10-065'
    'If ComboBox4.SelectedItem.ToString= '10-070'
    'If ComboBox4.SelectedItem.ToString = '10-080'
    '    If ComboBox4.SelectedItem.ToString = '12-030'
    'If ComboBox4.SelectedItem.ToString= '12-035'
    'If ComboBox4.SelectedItem.ToString = '12-040'
    'If ComboBox4.SelectedItem.ToString= '12-045'
    'If ComboBox4.SelectedItem.ToString = '12-050'
    '    If ComboBox4.SelectedItem.ToString = '16-030'
    'If ComboBox4.SelectedItem.ToString= '16-035'
    'If ComboBox4.SelectedItem.ToString = '16-040'
    'If ComboBox4.SelectedItem.ToString= '16-045'
    'If ComboBox4.SelectedItem.ToString = '16-050'

    'FHC

    '    If ComboBox3.SelectedItem.ToString = '4-08'
    'If ComboBox3.SelectedItem.ToString= '5-08'
    'If ComboBox3.SelectedItem.ToString = '6-08'
    'If ComboBox3.SelectedItem.ToString= '4-010'
    'If ComboBox3.SelectedItem.ToString = '5-010'
    'If ComboBox3.SelectedItem.ToString= '6-010'
    'If ComboBox3.SelectedItem.ToString = '4-012'
    'If ComboBox3.SelectedItem.ToString= '5-012'
    'If ComboBox3.SelectedItem.ToString = '6-012'
    'If ComboBox3.SelectedItem.ToString= '4-016'
    'If ComboBox3.SelectedItem.ToString = '5-016'
    'If ComboBox3.SelectedItem.ToString= '6-016'
    'If ComboBox3.SelectedItem.ToString = '4-018'
    'If ComboBox3.SelectedItem.ToString= '5-018'
    'If ComboBox3.SelectedItem.ToString = '6-018'
    'If ComboBox3.SelectedItem.ToString= '4-020'
    'If ComboBox3.SelectedItem.ToString = '5-020'
    'If ComboBox3.SelectedItem.ToString= '6-020'
    '    If ComboBox3.SelectedItem.ToString = '4-025'
    'If ComboBox3.SelectedItem.ToString= '5-025'
    'If ComboBox3.SelectedItem.ToString = '6-025'
    'If ComboBox3.SelectedItem.ToString= '4-030'
    'If ComboBox3.SelectedItem.ToString = '5-030'
    '    'If ComboBox3.SelectedItem.ToString= '6-030'
    '    If ComboBox3.SelectedItem.ToString = '8-010'
    'If ComboBox3.SelectedItem.ToString= '8-012'
    'If ComboBox3.SelectedItem.ToString = '8-016'
    'If ComboBox3.SelectedItem.ToString= '8-018'
    'If ComboBox3.SelectedItem.ToString = '8-020'
    '    If ComboBox3.SelectedItem.ToString = '8-025'
    'If ComboBox3.SelectedItem.ToString= '8-030'
    '    If ComboBox3.SelectedItem.ToString = '10-016'
    'If ComboBox3.SelectedItem.ToString= '10-018'
    'If ComboBox3.SelectedItem.ToString = '10-020'
    '    If ComboBox3.SelectedItem.ToString = '10-025'
    'If ComboBox3.SelectedItem.ToString= '10-030'
    'If ComboBox3.SelectedItem.ToString = '10-035'
    'H
    '    If ComboBox3.SelectedItem.ToString = '4-08'
    'If ComboBox3.SelectedItem.ToString= '4-012'
    'If ComboBox3.SelectedItem.ToString = '4-016'
    'If ComboBox3.SelectedItem.ToString= '4-020'
    'If ComboBox3.SelectedItem.ToString= '4-025'
    'If ComboBox3.SelectedItem.ToString= '4-030'
    'If ComboBox3.SelectedItem.ToString= '4-035'
    'If ComboBox3.SelectedItem.ToString= '4-040'
    'If ComboBox3.SelectedItem.ToString= '5-010'
    'If ComboBox3.SelectedItem.ToString= '5-012'
    'If ComboBox3.SelectedItem.ToString= '5-016'
    'If ComboBox3.SelectedItem.ToString= '5-018'
    'If ComboBox3.SelectedItem.ToString= '5-020'
    'If ComboBox3.SelectedItem.ToString= '5-025'
    'If ComboBox3.SelectedItem.ToString= '5-030'
    'If ComboBox3.SelectedItem.ToString= '5-035'
    'If ComboBox3.SelectedItem.ToString= '5-040'
    'If ComboBox3.SelectedItem.ToString= '5-045'
    'If ComboBox3.SelectedItem.ToString= '5-050'
    'If ComboBox3.SelectedItem.ToString= '6-012'
    'If ComboBox3.SelectedItem.ToString= '6-016'
    'If ComboBox3.SelectedItem.ToString= '6-020'
    'If ComboBox3.SelectedItem.ToString= '6-025'
    'If ComboBox3.SelectedItem.ToString= '6-030'
    'If ComboBox3.SelectedItem.ToString= '6-035'
    'If ComboBox3.SelectedItem.ToString= '6-040'
    'If ComboBox3.SelectedItem.ToString= '6-045'
    'If ComboBox3.SelectedItem.ToString= '6-050'
    'If ComboBox3.SelectedItem.ToString= '6-055'
    'If ComboBox3.SelectedItem.ToString= '6-060'
    'If ComboBox3.SelectedItem.ToString= '8-012'
    'If ComboBox3.SelectedItem.ToString= '8-016'
    'If ComboBox3.SelectedItem.ToString= '8-020'
    'If ComboBox3.SelectedItem.ToString= '8-025'
    'If ComboBox3.SelectedItem.ToString= '8-030'
    'If ComboBox3.SelectedItem.ToString= '8-035'
    'If ComboBox3.SelectedItem.ToString= '8-040'
    'If ComboBox3.SelectedItem.ToString= '8-045'
    'If ComboBox3.SelectedItem.ToString= '8-050'
    'If ComboBox3.SelectedItem.ToString= '8-055'
    'If ComboBox3.SelectedItem.ToString= '8-060'
    'If ComboBox3.SelectedItem.ToString= '8-065'
    'If ComboBox3.SelectedItem.ToString= '8-070'
    'If ComboBox3.SelectedItem.ToString= '8-075'
    'If ComboBox3.SelectedItem.ToString= '8-080'
    'If ComboBox3.SelectedItem.ToString= '8-090'
    'If ComboBox3.SelectedItem.ToString= '8-0100'
    'If ComboBox3.SelectedItem.ToString= '10-020'
    'If ComboBox3.SelectedItem.ToString= '10-025'
    'If ComboBox3.SelectedItem.ToString= '10-030'
    'If ComboBox3.SelectedItem.ToString= '10-035'
    'If ComboBox3.SelectedItem.ToString= '10-040'
    'If ComboBox3.SelectedItem.ToString= '10-045'
    'If ComboBox3.SelectedItem.ToString= '10-050'
    'If ComboBox3.SelectedItem.ToString= '10-055'
    'If ComboBox3.SelectedItem.ToString= '10-060'
    'If ComboBox3.SelectedItem.ToString= '10-065'
    'If ComboBox3.SelectedItem.ToString= '10-070'
    'If ComboBox3.SelectedItem.ToString= '12-030'
    'If ComboBox3.SelectedItem.ToString= '12-035'
    'If ComboBox3.SelectedItem.ToString= '12-040'
    'If ComboBox3.SelectedItem.ToString= '12-045'
    'If ComboBox3.SelectedItem.ToString= '12-050'
    'If ComboBox3.SelectedItem.ToString= '16-030'
    'If ComboBox3.SelectedItem.ToString= '16-035'
    'If ComboBox3.SelectedItem.ToString= '16-040'
    'If ComboBox3.SelectedItem.ToString= '16-045'
    'If ComboBox3.SelectedItem.ToString= '16-050'

















End Class